# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0c\x66ile_service\",\n\x0cListFilesReq\x12\x12\n\x05limit\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit\"#\n\rListFilesResp\x12\x12\n\nfile_names\x18\x01 \x03(\t\"D\n\x0eSearchFilesReq\x12\x14\n\x0csearch_query\x18\x01 \x01(\t\x12\x12\n\x05limit\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit2\x9d\x01\n\x0b\x46ileService\x12\x44\n\tListFiles\x12\x1a.file_service.ListFilesReq\x1a\x1b.file_service.ListFilesResp\x12H\n\x0bSearchFiles\x12\x1c.file_service.SearchFilesReq\x1a\x1b.file_service.ListFilesRespb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTFILESREQ._serialized_start=36
  _LISTFILESREQ._serialized_end=80
  _LISTFILESRESP._serialized_start=82
  _LISTFILESRESP._serialized_end=117
  _SEARCHFILESREQ._serialized_start=119
  _SEARCHFILESREQ._serialized_end=187
  _FILESERVICE._serialized_start=190
  _FILESERVICE._serialized_end=347
# @@protoc_insertion_point(module_scope)
